server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true

openweathermap:
  api:
    url: http://api.openweathermap.org/data/2.5/weather
    apikey: 22ee18701c5d343f2e7484e0d3a1514a

app:
  cache-expiration-in-minutes: 60

logging:
  level:
    com.james.weather: info
